version: '3.1'
services:
  webserver:
    image: 'nginx:alpine'
    container_name: r2-reurb-test
    working_dir: /app
    volumes:
      - '.:/app'
      - '${PATH_PHP:-/home/aldeir/projetos-estudos}/r2-docker-compose-config/8.2/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '${APP_PORT:-8080}:80'
    networks:
      - app-networks-r2
  php-fpm:
    build: '${PATH_PHP:-/home/aldeir/projetos-estudos}/r2-docker-compose-config/8.2/phpdocker/php-fpm'
    working_dir: /app
    container_name: php8.2-r2-reurb
    volumes:
      - '.:/app'
      - '${PATH_PHP:-/home/aldeir/projetos-estudos}/r2-docker-compose-config/8.2/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    networks:
      - app-networks-r2
networks:
  app-networks-r2:
    driver: bridge
